# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/paddy',
                'doc_host': 'https://hgzech.github.io',
                'git_url': 'https://github.com/hgzech/paddy',
                'lib_path': 'paddy'},
  'syms': {'paddy.core': {'paddy.core.foo': ('core.html#foo', 'paddy/core.py')}}}
